# Generated by Django 5.2.5 on 2025-11-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_level',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_level_teacher', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='class_level',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='classes_taught', to='users.teacher'),
        ),
    ]
